name: Deploy Stellarbase

on:
  push:
    branches: ['master']
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env
    timeout-minutes: 15

    steps:
      - name: 🚀 SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            APP_DIR="/var/www/stellarbase"
            BRANCH="master"

            cd "$APP_DIR"

            git config --global safe.directory "$APP_DIR"

            git fetch --all --prune
            git checkout "$BRANCH"
            git reset --hard "origin/$BRANCH"

            sudo systemctl restart nginx
